{{- if .Values.enterprise.enabled -}}
{{- if .Values.gateway.podDisruptionBudget -}}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "mimir.gatewayFullname" . }}
  labels:
    {{- include "mimir.gatewayLabels" . | nindent 4 }}
    {{- if .Values.useGEMLabels }}{{- include "mimir.gemExtraLabels" . | nindent 4 }}{{- end }}
spec:
  selector:
    matchLabels:
      {{- include "mimir.gatewaySelectorLabels" . | nindent 6 }}
{{ toYaml .Values.gateway.podDisruptionBudget | indent 2 }}
{{- end -}}
{{- end -}}
